#!/bin/sh

mkdir -p opk
cp ./bin/sonic2013 opk/sonic2013
cp ./icon.png opk/icon.png

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=RetroEngine
Comment=Engine for S1/S2
Exec=sonic2013 %f
Icon=icon
Terminal=false
Type=Application
Categories=games;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

print '[Desktop Entry]
Type=Application
Name=RE (No browser)
Comment=Engine for S1/S2
Exec=sonic2013
Icon=icon
Terminal=false
Type=Application
Categories=games;
X-OD-NeedsDownscaling=true' > opk/nobrowser."$1".desktop

mksquashfs ./opk retroengine_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
